spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teacherDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#server:
#  port: 8182





#spring:
#  datasource:
#    url: jdbc:mysql://docker-mysql:3306/test?useSSL=false
#    username: user
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#server:
# port: 8193






