
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
service:
  host: http://localhost:8084
  allocation:
    findAll: /services/allocation
    findByEmployeeId: /services/allocation/findByEmployeeId