server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
zuul:
  routes:
    student:
      path: /student/**
      url: http://localhost:8192
    teacher:
      path: /teacher/**
      url: http://localhost:8193
    course:
      path: /course/**
      url: http://localhost:8191

#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  datacenter: Colombo-SriLanka
#  environment: production
##zuul:
##    routes:
##        book:
##            path: /book/**
##            url: http://localhost:8080
##        transaction:
##            path: /transaction/**
##            url: http://localhost:8081
##
#ribbon:
#  ReadTimeout: 600000
#  ConnectTimeout: 60000